<footer>
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<p>
					Made with <a href="https://github.com/AAACEC/crowdfunding"><i class="fa fa-heart"></i></a> by <a href="https://github.com/rmobis">Phapha</a>, inspired on <a href="http://ironsummitmedia.github.io/startbootstrap-freelancer">Freelancer</a>.
				</p>
				<p>
					Copyright &copy; AAACEC 2016
				</p>
			</div>
		</div>
	</div>
</footer>
